In [1]:
!pip install nltk gensim scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 31.4 MB/s eta 0:00:00


In [2]:
import nltk
nltk.download('punkt')

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec
import numpy as np


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [3]:
corpus = [
    "I love natural language processing",
    "Natural language processing is very interesting",
    "I love machine learning and NLP"
]

print("Corpus:")
for sentence in corpus:
    print(sentence)

Corpus:
I love natural language processing
Natural language processing is very interesting
I love machine learning and NLP


In [4]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print("\n--- Bag of Words (Count Occurrence) ---")
print("Vocabulary:", vectorizer.get_feature_names_out())
print("BoW Matrix:\n", X.toarray())


--- Bag of Words (Count Occurrence) ---
Vocabulary: ['and' 'interesting' 'is' 'language' 'learning' 'love' 'machine' 'natural'
 'nlp' 'processing' 'very']
BoW Matrix:
 [[0 0 0 1 0 1 0 1 0 1 0]
 [0 1 1 1 0 0 0 1 0 1 1]
 [1 0 0 0 1 1 1 0 1 0 0]]


In [5]:
bow_matrix = X.toarray()
normalized_bow = bow_matrix / bow_matrix.sum(axis=1, keepdims=True)

print("\n--- Normalized Bag of Words ---")
print(normalized_bow)


--- Normalized Bag of Words ---
[[0.         0.         0.         0.25       0.         0.25
  0.         0.25       0.         0.25       0.        ]
 [0.         0.16666667 0.16666667 0.16666667 0.         0.
  0.         0.16666667 0.         0.16666667 0.16666667]
 [0.2        0.         0.         0.         0.2        0.2
  0.2        0.         0.2        0.         0.        ]]


In [6]:
tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(corpus)

print("\n--- TF-IDF Representation ---")
print("Vocabulary:", tfidf.get_feature_names_out())
print("TF-IDF Matrix:\n", X_tfidf.toarray())


--- TF-IDF Representation ---
Vocabulary: ['and' 'interesting' 'is' 'language' 'learning' 'love' 'machine' 'natural'
 'nlp' 'processing' 'very']
TF-IDF Matrix:
 [[0.         0.         0.         0.5        0.         0.5
  0.         0.5        0.         0.5        0.        ]
 [0.         0.45954803 0.45954803 0.34949812 0.         0.
  0.         0.34949812 0.         0.34949812 0.45954803]
 [0.46735098 0.         0.         0.         0.46735098 0.35543247
  0.46735098 0.         0.46735098 0.         0.        ]]


In [8]:
nltk.download('punkt_tab')
tokenized_corpus = [nltk.word_tokenize(sentence.lower()) for sentence in corpus]

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [9]:
model = Word2Vec(sentences=tokenized_corpus, vector_size=100, window=5, min_count=1)

print("\n--- Word2Vec Embeddings ---")



--- Word2Vec Embeddings ---


In [10]:
print("\nVector for 'language':\n", model.wv['language'])


Vector for 'language':
 [-8.6196875e-03  3.6657380e-03  5.1898835e-03  5.7419385e-03
  7.4669183e-03 -6.1676754e-03  1.1056137e-03  6.0472824e-03
 -2.8400505e-03 -6.1735227e-03 -4.1022300e-04 -8.3689485e-03
 -5.6000124e-03  7.1045388e-03  3.3525396e-03  7.2256695e-03
  6.8002474e-03  7.5307419e-03 -3.7891543e-03 -5.6180597e-04
  2.3483764e-03 -4.5190323e-03  8.3887316e-03 -9.8581640e-03
  6.7646410e-03  2.9144168e-03 -4.9328315e-03  4.3981876e-03
 -1.7395747e-03  6.7113843e-03  9.9648498e-03 -4.3624435e-03
 -5.9933780e-04 -5.6956373e-03  3.8508223e-03  2.7866268e-03
  6.8910765e-03  6.1010956e-03  9.5384968e-03  9.2734173e-03
  7.8980681e-03 -6.9895042e-03 -9.1558648e-03 -3.5575271e-04
 -3.0998408e-03  7.8943167e-03  5.9385742e-03 -1.5456629e-03
  1.5109634e-03  1.7900408e-03  7.8175711e-03 -9.5101865e-03
 -2.0553112e-04  3.4691966e-03 -9.3897223e-04  8.3817719e-03
  9.0107834e-03  6.5365066e-03 -7.1162102e-04  7.7104042e-03
 -8.5343346e-03  3.2071066e-03 -4.6379971e-03 -5.0889552e-03

In [11]:
print("\nWords similar to 'language':")
print(model.wv.most_similar('language'))


Words similar to 'language':
[('love', 0.06797593832015991), ('machine', 0.03364057466387749), ('nlp', 0.009391162544488907), ('is', 0.008315950632095337), ('i', 0.0045030261389911175), ('processing', -0.010839177295565605), ('natural', -0.023671656847000122), ('interesting', -0.09575343877077103), ('and', -0.11410722136497498), ('learning', -0.11555545777082443)]


In [12]:
print("\n--- SUMMARY ---")
print("BoW Shape:", X.shape)
print("TF-IDF Shape:", X_tfidf.shape)
print("Word2Vec Vocabulary:", list(model.wv.index_to_key))


--- SUMMARY ---
BoW Shape: (3, 11)
TF-IDF Shape: (3, 11)
Word2Vec Vocabulary: ['processing', 'language', 'natural', 'love', 'i', 'nlp', 'and', 'learning', 'machine', 'interesting', 'very', 'is']
